
version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16

      # Specify service dependencies here if necessary
      - image: circleci/mongo:4.2

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install

      # run tests
      - run: npm test